import type { Metadata } from 'next';
import Script from 'next/script';
import '../styles/globals.css';
import { montserrat } from '@/styles/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Script
        async
        src="https://cloud.umami.is/script.js"
        data-website-id="a9c886d8-325d-438c-8309-836d7a4fd551"
        strategy="afterInteractive"
      />
      <body className={`${montserrat.className}`}>{children}</body>
    </html>
  );
}
